dist: xenial
language: C
sudo: false

branches:
  except:
    - gh-pages

addons:
  apt:
  apt_packages:
      - libgmp3-dev
      - parallel
      - valgrind
      - autotools-dev
      - automake
env:
  - BRANCH="master" CONF_FLAG="" 
  - BRANCH="stable-4.10" CONF_FLAG="" 
#  - BRANCH="hpcgap-default" CONF_FLAG="--enable-checking"
  - BRANCH="master" CONF_FLAG="--enable-checking" 
  - BRANCH="master" CONF_FLAG="--enable-timing" 
  - BRANCH="master" CONF_FLAG="--enable-checking --enable-timing" 
  


install:
  - echo $BRANCH ":" $CONF_FLAG
  - echo $CXX ":" $CC
  - git clone -b $BRANCH --depth=2 https://github.com/gap-system/gap.git gap
  - pwd
  - ( cd gap && ./autogen.sh || echo no autogen )
  - ( cd gap && ./configure && make && make bootstrap-pkg-full V=1)
  - ( cd gap/pkg && ../bin/BuildPackages.sh io* )
  - pwd
  - echo ln -s $(pwd) gap/pkg/ferret
  - ln -s $(pwd) gap/pkg/ferret
  - ( cd gap/pkg/ferret && ./autogen.sh && ./configure $CONF_FLAG && make V=1)
  - pwd
  - ls
  - ls gap
  - ls gap/pkg
  - cat ferret.vars

script:
  - (cd gap/pkg/ferret && scripts/quick_test.sh ${MAKEFLAG})
