name: ferret
version: "1.0.13"
license: "MPL-2.0"
date: 2024-09-01
description: |
    Backtrack Search in Permutation Groups

authors:
    - name: Christopher Jefferson
      url: https://heather.cafe/

maintainers:
    - name: Christopher Jefferson
      url: https://heather.cafe/

GAP: ">= 4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/ferret/
readme: README
packageinfo: https://gap-packages.github.io/ferret/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ferret/releases/download/v1.0.13/ferret-1.0.13.tar.gz

abstract: |
     The <span class="pkgname">Ferret</span> package provides a C++ reimplementation of Jeffery Leon's Partition Backtrack framework for solving problems in permutation groups

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Permutation Groups, Partition Backtrack.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Jef24</span>]   <b class='BibAuthor'>Jefferson, C.</b>,
     <i class='BibTitle'>ferret, Backtrack Search in Permutation Groups,
             Version 1.0.13</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/ferret/">https://gap-packages.github.io/ferret/</a></span>.
    </p>
    

bibtex: |
    @misc{ ferret,
      author =           {Jefferson, C.},
      title =            {{ferret},  Backtrack  Search  in  Permutation  Groups,
                          {V}ersion 1.0.13},
      month =            {Sep},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href         {https://gap-packages.github.io/ferret/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{ferret/}}},
      keywords =         {Permutation Groups; Partition Backtrack},
      printedkey =       {Jef24}
    }

