name: ferret
version: 1.0.8
date: 2022-07-01
description: |
    Backtrack Search in Permutation Groups

authors:
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.11"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/ferret/
readme: README
packageinfo: https://gap-packages.github.io/ferret/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/ferret/releases/download/v1.0.8/ferret-1.0.8.tar.gz

abstract: |
     The <span class="pkgname">Ferret</span> package provides a C++ reimplementation of Jeffery Leon's Partition Backtrack framework for solving problems in permutation groups

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
