#ifndef TUNABLES_HPP_FDSJIOVDS
#define TUNABLES_HPP_FDSJIOVDS


#define TUNABLE_STABCHAIN_MERGE_DIST 100
#define TUNABLE_STABCHAIN_RECORD_ALL_PERMS 0
#define TUNABLE_ALWAYS_SORT 1

#define TUNABLE_SKIP_EMPTY_BLOCKS 0
#define TUNABLE_FILTER_SINGLE_CELLS 1
#endif
