name: CI

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the default repository branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref_name != github.event.repository.default_branch || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  # The CI test job
  test:
    name: GAP ${{ matrix.gap-branch }} ${{ matrix.flags }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.15
          - stable-4.14
          - stable-4.13
          - stable-4.12
        flags:
          - ''
        # additional jobs with special flags
        include:
          - gap-branch: 'master'
            flags: '--enable-checking'
          - gap-branch: 'master'
            flags: '--enable-timing'
          - gap-branch: 'master'
            flags: '--enable-checking --enable-timing'

    steps:
      - uses: actions/checkout@v5

      - name: 'Install needed apt_packages'
        shell: bash
        run: |
          packages=(
            libgmp3-dev
            valgrind
          )
          sudo apt-get update
          sudo apt-get install "${packages[@]}"

      - name: 'Build GAP and its packages'
        uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap-branch }}

      - name: 'Build ferret'
        uses: gap-actions/build-pkg@v1
        with:
          CONFIGFLAGS: ${{ matrix.flags }}

      - name: 'Run ferret GAP tests'
        uses: gap-actions/run-pkg-tests@v3

      - name: 'Run YAPB++ tests'
        run:  cd YAPB++/tests && ./run_tests.sh

      - name: 'Run Valgrind tests'
        run: |
            valgrind -q --trace-children=yes --suppressions=scripts/gap-suppressions.valgrind gap -A -q -l "/tmp/gaproot;" tst/testvalgrind.g

      - uses: gap-actions/process-coverage@v2
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
