name: 'ferret CI'

on:
  push:
    branches:
      - master
  pull_request:

# the `concurrency` settings ensure that not too many CI jobs run in parallel
concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: GAP ${{ matrix.gap }} ${{ matrix.flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gap:
          - 'master'
        flags:
          - ''
          - '--enable-checking'
          - '--enable-timing'
          - '--enable-checking --enable-timing'

        include:
          - gap: 'stable-4.13'
            flags: ''
          - gap: 'stable-4.12'
            flags: ''

    steps:
      - uses: actions/checkout@v4

      - name: 'Install needed apt_packages'
        shell: bash
        run: |
          packages=(
            libgmp3-dev
            valgrind
          )
          sudo apt-get update
          sudo apt-get install "${packages[@]}"

      - name: 'Build GAP and its packages'
        uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: ${{ matrix.gap }}

      - name: 'Build ferret'
        uses: gap-actions/build-pkg@v1
        with:
          CONFIGFLAGS: ${{ matrix.flags }}

      - name: 'Run ferret GAP tests'
        uses: gap-actions/run-pkg-tests@v2

      - name: 'Run YAPB++ tests'
        run:  cd YAPB++/tests && ./run_tests.sh

      - name: 'Run Valgrind tests'
        run: |
            valgrind -q --trace-children=yes --suppressions=scripts/gap-suppressions.valgrind gap -A -q -l "/tmp/gaproot;" tst/testvalgrind.g
